services:
  frontend:
    build:
      context: .
      target: dev
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public:ro
      - ./src:/app/src:ro
    develop:
      watch:
        - path: ./package-lock.json
          action: rebuild
        - path: .
          target: /app
          action: sync


    
