# Simple Air config
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/server ./cmd/rip"
bin = "tmp/server"
full_bin = "APP_ENV=dev ./tmp/server"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp"]
