[Public]
Host = "localhost"

[Service]
Host = "0.0.0.0"
Port = 8000

[S3]
Host = "minio"
Port = 9000

[JWT]
Token = "turbines-secret-token"
SigningMethod = "HS256"
ExpiresIn = "24h"

[Redis]
Host        = "redis"
Password    = "password"
Port        = 6379
User        = ""
DialTimeout = "10s"
ReadTimeout = "10s"