[Public]
Host = "10.185.38.237"

[Service]
Host = "0.0.0.0"
Port = 8000

[S3]
Host = "minio"
Port = 9000

[JWT]
Token = "turbines-secret-token"
SigningMethod = "HS256"
ExpiresIn = "24h"

[Redis]
DialTimeout = "10s"
ReadTimeout = "10s"